let Meta = {
  keywords: [
    "University of Minnesota",
    "University of Minnesota - Twin Cities",
    "Prerequisite",
    "Prerequisites",
    "Interactive Prerequisite",
    "Interactive Prerequisites",
    "Interactive Prerequisite Flowchart",
    "Interactive Prerequisites Flowchart",
    "Gopher Flow",
    "Course Flowchart",
    "Course chart",
    "Gopher Prerequisite",
    "Gopher Prerequisites",
    "UMN Course Planning",
    "UMN Academic Advising",
    "Degree Requirements UMN",
    "Major Requirement Guide",
    "Course Registration UMN",
    "Academic Resources UMN",
    "University Course Guide",
    "Educational Planning Tools",
    "Student Academic Support",
    "UMN Course Mapping",
    "Curriculum Mapping UMN",
    "Gopher Academic Planning",
    "Online Education Resources UMN",
    "UMN Class Schedule",
    "University of Minnesota Course Catalog",
  ],
};

export const Keywords = Meta.keywords.join(", ");
